baseURL = '/'
languageCode = "en-us"
title = "Visa Limbo"
theme = "hugo-ink"
paginate = 5
HUGO_VERSION = '0.89.4'

#copyright = "Â© Copyright notice"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "ink-demo"

[params]
  subtitle = "[How long are waiting times for US visa appointments?](https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/wait-times.html)"

	# Optional 64x64 avatar image.
	avatar =  "https://i.ibb.co/3rgTynP/Dali-limbo.png"
	# http://vsemart.com/wp-content/uploads/2014/07/Flexible-clock.jpg

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
#[[menu.main]]
#name = "Home"
#url = "/"
#weight = 1

#[[menu.main]]
#name = "All posts"
#url = "/posts"
#weight = 2

#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 3

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/VisaLimbo"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/VisaLimbo"

[taxonomies]
   tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


     
